# Generated by Django 2.1.7 on 2019-02-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190207_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='accreditation_type',
            field=models.CharField(choices=[('R', 'Regional'), ('N', 'National')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='accredited',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='admin_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='admin_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='admin_phone',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='admissions_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='application_fee_waived',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='city',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='clep_credits_accepted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='dsst_credits_accepted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='external_id',
            field=models.PositiveIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='four_year_program',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='graduate_graduation_rate',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='jst_credits_accepted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='online_credits_accepted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='private',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='regional_accreditor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='standardized_test_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='standardized_test_required',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='state',
            field=models.CharField(default='NY', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='student_population',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='sva_chapter',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='two_year_program',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='undergrad_graduation_rate',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='veteran_center',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='veteran_grants_scholarships',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='veteran_grants_scholarships_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='veteran_population',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='website_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='yellow_ribbon',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='yellow_ribbon_contribution',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='yellow_ribbon_slots',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
