# Generated by Django 2.1.7 on 2019-02-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190214_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='graduate_graduation_rate',
            new_name='grad_vet_graduation_rate',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='undergrad_graduation_rate',
            new_name='undergrad_vet_graduation_rate',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='veteran_population',
            new_name='undergrad_vet_population',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='veteran_center',
            new_name='vet_center',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='veteran_grants_scholarships',
            new_name='vet_grants_scholarships',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='veteran_grants_scholarships_notes',
            new_name='vet_grants_scholarships_notes',
        ),
        migrations.AddField(
            model_name='institution',
            name='grad_vet_population',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
