# Generated by Django 2.1.7 on 2019-02-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190216_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='accreditation_type',
            field=models.CharField(choices=[('R', 'regional'), ('N', 'national')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='yellow_ribbon_contribution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='yellow_ribbon_slots',
            field=models.TextField(blank=True, null=True),
        ),
    ]
