# Generated by Django 2.1.7 on 2019-03-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190227_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='undergraduate_population',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
