# Generated by Django 2.1.7 on 2019-03-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_institution_undergraduate_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='admin_email',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='admin_name',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='admin_phone',
        ),
    ]
