# Generated by Django 3.2.12 on 2022-03-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190328_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='title',
            field=models.TextField(),
        ),
    ]
