# Generated by Django 3.2.12 on 2022-03-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_institution_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='external_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
